# types for ml-metadata library
artifact-types:
  - name: "mlschema.Model"
  - name: "mlschema.ModelEvaluation"
  - name: "mlschema.EvaluationMeasure"
  - name: "mlschema.EvaluationSpecification"
  - name: "mlschema.EvaluationProcedure"
  - name: "mlschema.Task"
  - name: "mlschema.Data"
  - name: "mlschema.DataSet"
  - name: "mlschema.Feature"
  - name: "mlschema.Algorithm"
  - name: "mlschema.Software"
  - name: "mlschema.Implementation"
  - name: "mlschema.HyperParameter"
  - name: "mlschema.HyperParameterSetting"
  - name: "mlschema.ImplementationCharacteristic"
  - name: "mlschema.DatasetCharacteristic"
  - name: "mlschema.FeatureCharacteristic"
context-types:
  - name: "mlschema.RegisteredModel"
  - name: "mlschema.ModelVersion"
  - name: "mlschema.DataCharacteristic"
execution-types:
  - name: "mlschema.Study"
  - name: "mlschema.Experiment"
  - name: "mlschema.Run"
